import { useEffect, useRef, useState } from 'react'
import { Plus, RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { formatUserError } from '../lib/errors'

type Product = { product_id: string; loan_code: string; minimum_principal: number; maximum_principal: number | null; minimum_tenor_months: number; maximum_tenor_months: number; rate: number; products: { code: string; name: string } | null }

export function ManagerLoanProducts() {
  const guard = useRef(false)
  const [busy, setBusy] = useState(false)
  const [loading, setLoading] = useState(true)
  const [items, setItems] = useState<Product[]>([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState(''); const [form, setForm] = useState({ code: '', name: '', loanCode: '', min: '1000000', max: '5000000', minTenor: '1', maxTenor: '12', rate: '0', tenors: '6,12,18,24', adminType: 'FIXED', adminValue: '0', terms: '' })
  const load = async () => { setLoading(true); const { data, error } = await supabase.from('loan_products').select('product_id,loan_code,minimum_principal,maximum_principal,minimum_tenor_months,maximum_tenor_months,rate,products(code,name)').order('loan_code'); if (error) setMessage(formatUserError(error)); else setItems((data ?? []) as unknown as Product[]); setLoading(false) }
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [])
  const save = async () => { if (guard.current) return; guard.current = true; setBusy(true); setMessage(''); try { const tenors = form.tenors.split(',').map((item) => Number(item.trim())).filter((item) => Number.isInteger(item) && item > 0); if (!form.code.trim() || !form.name.trim() || !form.loanCode.trim() || Number(form.min) <= 0 || Number(form.max) < Number(form.min) || Number(form.rate) < 0 || !tenors.length) throw new Error('Lengkapi kode/nama, batas nominal, margin, dan pilihan tenor.'); await supabase.rpc('manager_create_murabahah_product', { p_code: form.code.trim().toUpperCase(), p_name: form.name.trim(), p_loan_code: form.loanCode.trim(), p_minimum_principal: Number(form.min), p_maximum_principal: Number(form.max), p_tenor_options: tenors, p_margin_rate: Number(form.rate), p_admin_fee_type: form.adminType, p_admin_fee_value: Number(form.adminValue), p_terms_and_conditions: form.terms.trim() || undefined }).throwOnError(); setMessage('Produk pembiayaan murabahah berhasil ditambahkan.'); setOpen(false); await load() } catch (error) { setMessage(formatUserError(error)) } finally { guard.current = false; setBusy(false) } }
  return <section className="rounded-2xl border border-[#dce8d8] bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Produk pembiayaan</h3><p className="text-sm text-[#475569]">Atur akad murabahah, nominal, tenor, margin, biaya, dan syarat produk.</p></div><div className="flex gap-2"><button type="button" aria-label="Muat ulang produk" disabled={loading} onClick={() => void load()} className="min-h-11 rounded-xl border px-3"><RefreshCw size={16} /></button><button type="button" onClick={() => setOpen((v) => !v)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#16843a] px-4 text-sm font-semibold text-white"><Plus size={16} /> Tambah produk</button></div></div>{open && <div className="mt-4 grid gap-3 sm:grid-cols-2">{[['code','Kode produk'],['name','Nama produk'],['loanCode','Kode kredit'],['min','Nominal minimum'],['max','Nominal maksimum'],['rate','Margin (%)'],['tenors','Pilihan tenor (contoh: 6,12,18,24)'],['adminValue','Biaya admin'],['terms','Syarat dan ketentuan']].map(([key,label]) => <label key={key} className="text-sm">{label}<input value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} type={['min','max','rate','adminValue'].includes(key) ? 'number' : 'text'} className="mt-1 w-full rounded-xl border p-3" /></label>)}<button type="button" disabled={busy} onClick={() => void save()} className="min-h-11 rounded-xl bg-[#1d7042] px-4 font-semibold text-white sm:col-span-2">{busy ? 'Menyimpan…' : 'Simpan produk murabahah'}</button></div>}{loading && <p role="status">Memuat produk…</p>}{!loading && !items.length && <p>Belum ada produk yang dapat ditampilkan.</p>}<div className="mt-4 space-y-2">{items.map((item) => <div key={item.product_id} className="rounded-xl bg-[#f5f9f3] p-3 text-sm"><strong>{item.products?.name ?? item.loan_code}</strong><span className="ml-2 text-[#475569]">{item.loan_code} · Rp {Number(item.minimum_principal).toLocaleString('id-ID')}–{item.maximum_principal == null ? '∞' : Number(item.maximum_principal).toLocaleString('id-ID')} · {item.minimum_tenor_months}–{item.maximum_tenor_months} bulan · margin {item.rate}%</span></div>)}</div>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</section>
}
