import { useEffect, useState } from 'react'
import { LockKeyholeOpen, LockKeyhole, CheckCircle2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { formatUserError } from '../lib/errors'
import type { Database } from '../types/database'

type Session = Database['bmt_db']['Functions']['teller_get_cash_session']['Returns'][number]
export function TellerCashSession({ onChange }: { onChange: (open: boolean) => void }) {
  const [session, setSession] = useState<Session | null>(null); const [opening, setOpening] = useState(''); const [closing, setClosing] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const load = async () => { const result = await supabase.rpc('teller_get_cash_session'); if (!result.error) { const current = result.data?.[0] ?? null; setSession(current); onChange(current?.status === 'OPEN') } else setError(formatUserError(result.error)) }
  useEffect(() => { let active = true; void supabase.rpc('teller_get_cash_session').then((result) => { if (active && !result.error) { const current = result.data?.[0] ?? null; setSession(current); onChange(current?.status === 'OPEN') } }); return () => { active = false } }, [onChange])
  const open = async () => { setBusy(true); setError(''); try { const result = await supabase.rpc('teller_open_cash_session', { p_opening_balance: Number(opening) }); if (result.error) throw result.error; setMessage('Sesi kas berhasil dibuka.'); await load() } catch (cause) { setError(formatUserError(cause)) } finally { setBusy(false) } }
  const close = async () => { setBusy(true); setError(''); try { const result = await supabase.rpc('teller_close_cash_session', { p_physical_closing_balance: Number(closing) }); if (result.error) throw result.error; const row = result.data?.[0]; setMessage(`Sesi kas ditutup. Selisih: Rp ${Number(row?.difference ?? 0).toLocaleString('id-ID')}`); await load() } catch (cause) { setError(formatUserError(cause)) } finally { setBusy(false) } }
  if (!session || session.status !== 'OPEN') return <section className="role-panel border-amber-200 bg-amber-50" aria-label="Sesi kas teller"><div className="flex items-center gap-3"><LockKeyholeOpen className="text-amber-700" /><div><h2 className="font-bold">Buka sesi kas teller</h2><p className="text-sm text-slate-600">Teller tidak dapat menerima setoran sebelum memasukkan saldo awal fisik kas.</p></div></div><div className="mt-4 flex flex-wrap gap-3"><input type="number" min="0" value={opening} onChange={(event) => setOpening(event.target.value)} className="min-h-11 rounded-xl border p-3" placeholder="Saldo awal kas" /><button type="button" disabled={busy || opening === ''} onClick={() => void open()} className="min-h-11 rounded-xl bg-green-800 px-4 font-semibold text-white disabled:opacity-50">{busy ? 'Membuka…' : 'Buka sesi kas'}</button></div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{message && <p role="status" className="mt-3 flex items-center gap-2 text-sm text-green-800"><CheckCircle2 size={16} />{message}</p>}</section>
  return <section className="role-panel border-green-200 bg-green-50" aria-label="Sesi kas teller"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><LockKeyhole className="text-green-700" /><div><h2 className="font-bold">Sesi kas aktif</h2><p className="text-sm text-slate-600">Saldo awal: Rp {Number(session.opening_balance).toLocaleString('id-ID')}</p><p className="text-sm font-semibold text-green-800">Saldo kas sistem: Rp {Number(session.system_balance).toLocaleString('id-ID')}</p></div></div><span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-800">OPEN</span></div><div className="mt-4 flex flex-wrap gap-3"><input type="number" min="0" value={closing} onChange={(event) => setClosing(event.target.value)} className="min-h-11 rounded-xl border p-3" placeholder="Kas fisik akhir hari" /><button type="button" disabled={busy || closing === ''} onClick={() => void close()} className="min-h-11 rounded-xl bg-slate-800 px-4 font-semibold text-white disabled:opacity-50">{busy ? 'Menutup…' : 'Tutup sesi kas'}</button><button type="button" onClick={() => void load()} className="min-h-11 rounded-xl border px-4">Perbarui kas</button></div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{message && <p role="status" className="mt-3 flex items-center gap-2 text-sm text-green-800"><CheckCircle2 size={16} />{message}</p>}</section>
}
